# Portable native-R rendering, URI safety, and all-AI regression checks.
if (!exists("to_png", mode = "function")) {
  root <- if (dir.exists("R")) "." else if (dir.exists("../R")) ".." else "specqr-r-work/SpecQR-R"
  for (file in sort(list.files(file.path(root, "R"), pattern = "[.]R$", full.names = TRUE))) source(file)
}
.rg_checks <- 0L
.rg_check <- function(ok) { .rg_checks <<- .rg_checks + 1L; if (!isTRUE(ok)) stop("Render/GS1 check failed at ", .rg_checks) }
.rg_error <- function(expr, code = "INVALID_GS1", detail = NULL) {
  e <- tryCatch({ force(expr); NULL }, error = identity)
  .rg_check(inherits(e, "specqr_error") && identical(e$code, code) && (is.null(detail) || identical(e$detail_code, detail)))
}
.rg_same <- function(a, b) .rg_check(isTRUE(all.equal(a, b, check.attributes = FALSE)))
.rg_check(length(get_supported_gs1_ais()) == 50L)
.rg_check(is.null(get_gs1_ai_info("3106")))
.rg_check(is.null(get_gs1_ai_info(1)))
for (info in get_supported_gs1_ais()) {
  size <- if (info$length$is_variable) 1L else info$length$exact
  value <- paste0(rep(if (info$value_kind == "text") "A" else "0", size), collapse = "")
  e <- list(list(ai = info$ai, value = value))
  .rg_check(validate_gs1_elements(e)$ok)
  .rg_same(parse_gs1_human_readable(gs1_to_human_readable(e)), e)
  .rg_same(parse_gs1_element_string(create_gs1_element_string(e))$elements, e)
  bad <- list(list(ai = info$ai, value = paste0(rep("A", if (info$length$is_variable) info$length$max + 1L else info$length$exact + 1L), collapse = "")))
  .rg_check(!validate_gs1_elements(bad)$ok)
}
.rg_same(calculate_gs1_check_digit("1234567890123"), "1")
.rg_same(append_gtin_check_digit("0950600013435"), "09506000134352")
.rg_check(validate_gtin_check_digit("09506000134352"))
.rg_check(!validate_gtin_check_digit("09506000134353"))
.rg_same(append_sscc_check_digit("12345678901234567"), "123456789012345675")
.rg_check(validate_sscc_check_digit("123456789012345675"))
for (bad in list(NULL, NA_character_, c("1", "2"), 123, TRUE, "", "abc", "\u0661")) .rg_error(calculate_gs1_check_digit(bad))
.rg_error(calculate_gtin_check_digit("123"), detail = "GS1_INVALID_LENGTH")
.rg_error(validate_sscc_check_digit("123"), detail = "GS1_INVALID_LENGTH")
.rg_error(validate_gs1_check_digit("1"), detail = "GS1_INVALID_LENGTH")
items <- parse_gs1_human_readable("(01)09506000134352(10)LOT%1(17)251231(21)SN-A")
raw <- create_gs1_element_string(items)
.rg_check(grepl("10LOT%1\x1d17", raw, fixed = TRUE))
.rg_same(gs1_to_human_readable(items), "(01)09506000134352(10)LOT%1(17)251231(21)SN-A")
.rg_same(normalize_gs1_elements(raw), items)
.rg_same(normalize_gs1_elements(gs1_to_human_readable(items)), items)
.rg_same(normalize_gs1_elements(items), items)
.rg_check(parse_gs1_element_string(raw)$has_separators)
.rg_error(parse_gs1_element_string("10ABC17251231"), detail = "GS1_MISSING_SEPARATOR")
for (bad in c("\x1d10ABC", "10ABC\x1d", "10ABC\x1d\x1d17251231")) .rg_error(parse_gs1_element_string(bad), detail = "GS1_UNEXPECTED_SEPARATOR")
for (bad in c("", "(01", "01)09506000134352", "(01)09506000134353", "(10)A)B", "(777)A", "(10)\u00e9", "(10)\n")) .rg_error(parse_gs1_human_readable(bad))
.rg_error(parse_gs1_element_string("(10)ABC"))
.rg_error(create_gs1_element_string(list()))
.rg_error(create_gs1_element_string(list(list(ai = 10, value = "ABC"))))
.rg_error(create_gs1_element_string(list(list(ai = "10", value = 123))))
.rg_error(create_gs1_element_string(list(list(ai = "10", value = "A(B"))))
.rg_error(create_gs1_element_string(list(list(ai = "10", value = "A\x1dB"))), detail = "GS1_UNEXPECTED_SEPARATOR")
.rg_error(create_gs1_element_string(rep(list(list(ai = "10", value = "A")), GS1_MAX_ELEMENTS + 1L)))
.rg_error(parse_gs1_human_readable(paste0(rep("A", GS1_MAX_INPUT_CHARACTERS + 1L), collapse = "")))
invalid <- list(list(ai = "777", value = "A"), list(ai = "01", value = "09506000134353"))
.rg_check(length(validate_gs1_elements(invalid)$errors) == 2L)
.rg_check(length(validate_gs1_elements(invalid, collect_all_errors = FALSE)$errors) == 1L)
.rg_same(validate_gs1_elements(invalid)$errors[[2L]]$element_index, 1L)
.rg_check(!validate_gs1_elements(list(list(ai = "10", value = "A")), context = "digital-link")$ok)
.rg_check(!validate_gs1_elements(items, allow_unsupported_ai = TRUE)$ok)
.rg_check(!validate_gs1_elements(items, collect_all_errors = NA)$ok)
.rg_check(!validate_gs1_elements(items, context = "other")$ok)
.rg_check(validate_gs1_element_string(raw)$ok)
.rg_check(!validate_gs1_element_string("10ABC17251231")$ok)
link <- create_gs1_digital_link(items, base_url = "HTTPS://EXAMPLE.COM:443/base")
.rg_same(link, "https://example.com/base/01/09506000134352/10/LOT%251/21/SN-A?17=251231")
parsed <- parse_gs1_digital_link(link)
.rg_same(parsed$primary, items[[1L]])
.rg_same(vapply(parsed$path_elements, `[[`, "", "ai"), c("01", "10", "21"))
.rg_same(vapply(parsed$query_elements, `[[`, "", "ai"), "17")
.rg_same(normalize_gs1_digital_link(link), link)
.rg_same(create_gs1_digital_link(items, base_url = "https://example.com", path_ais = character()), "https://example.com/01/09506000134352?10=LOT%251&17=251231&21=SN-A")
base <- "https://example.com/01/09506000134352"
unknown <- paste0(base, "?x=1&x=2&empty&10=.&dots=..&emoji=%F0%9F%98%80")
u <- parse_gs1_digital_link(unknown)
.rg_check(length(u$unknown_query) == 5L)
.rg_same(u$query_elements[[1L]]$value, ".")
.rg_same(normalize_gs1_digital_link(unknown), paste0(base, "?10=.&x=1&x=2&empty=&dots=..&emoji=%F0%9F%98%80"))
.rg_error(parse_gs1_digital_link(unknown, unknown_query = "reject"), detail = "GS1_DIGITAL_LINK_UNKNOWN_QUERY")
.rg_error(parse_gs1_digital_link(base, unknown_query = NA_character_))
.rg_error(parse_gs1_digital_link(paste0(base, "?10=A&10=B")), detail = "GS1_DUPLICATE_AI")
.rg_error(create_gs1_digital_link(c(items, items[1L]), base_url = "https://example.com"), detail = "GS1_DUPLICATE_AI")
.rg_error(create_gs1_digital_link(items))
.rg_error(create_gs1_digital_link(items, base_url = "https://example.com?"))
.rg_error(create_gs1_digital_link(items, base_url = "https://example.com", path_ais = "17"), detail = "GS1_INVALID_DIGITAL_LINK_PLACEMENT")
.rg_error(create_gs1_digital_link(items, base_url = "https://example.com/%30%31"), detail = "GS1_INVALID_DIGITAL_LINK_PLACEMENT")
.rg_same(create_gs1_digital_link(items[1L], base_url = "https://example.com/a/../b/./"), "https://example.com/b/01/09506000134352")
for (dot in c(".", "..", "%2e", "%2E%2e", ".%2e")) .rg_error(parse_gs1_digital_link(paste0(base, "/10/", dot)), detail = "GS1_INVALID_DIGITAL_LINK_PLACEMENT")
.rg_same(parse_gs1_digital_link(paste0(base, "/10/%252e"))$path_elements[[2L]]$value, "%2e")
.rg_same(normalize_gs1_digital_link(paste0(base, "?10=..")), paste0(base, "?10=.."))
.rg_error(parse_gs1_digital_link(paste0(base, "/17/251231")), detail = "GS1_INVALID_DIGITAL_LINK_PLACEMENT")
.rg_error(parse_gs1_digital_link(paste0(base, "/10")))
.rg_error(parse_gs1_digital_link(paste0(base, "//10/A")))
.rg_error(parse_gs1_digital_link(paste0(base, "#")), detail = "GS1_DIGITAL_LINK_FRAGMENT_NOT_ALLOWED")
for (suffix in c("%", "%2", "%GG", "%FF", "%C0%AF", "%ED%A0%80", "%F4%90%80%80", "%00")) .rg_error(parse_gs1_digital_link(paste0(base, "?unknown=", suffix)), detail = "GS1_INVALID_PERCENT_ENCODING")
for (host in c("0x", "0X", "1.0x", "example.0x", "0x.", "127.1", "2130706433", "127.0.0.01", "127.0.0.1.", "999.0.0.1", "user@example.com", "ex%61mple.com", "-example.com", "example-.com", "a..b", "\u00e9.com", "[1:2:3]", "[1::2::3]", "[::ffff:192.168.001.1]", "[fe80::1%25eth0]")) .rg_error(parse_gs1_digital_link(paste0("https://", host, "/01/09506000134352")), detail = "GS1_DIGITAL_LINK_UNSUPPORTED_HOST")
for (host in c("example.com", "EXAMPLE.COM.", "127.0.0.1", "[::1]", "[2001:DB8::1]", "[::ffff:192.0.2.1]", "[1:2:3:4:5:6:7:8]")) .rg_check(validate_gs1_digital_link(paste0("https://", host, "/01/09506000134352"))$ok)
for (port in c("", "-1", "65536", "000443", "abc", "1:2")) .rg_error(parse_gs1_digital_link(paste0("https://example.com:", port, "/01/09506000134352")), detail = "GS1_DIGITAL_LINK_INVALID_URI")
.rg_same(normalize_gs1_digital_link("http://EXAMPLE.COM:00080/01/09506000134352"), "http://example.com/01/09506000134352")
.rg_same(normalize_gs1_digital_link("https://EXAMPLE.COM:00081/01/09506000134352"), "https://example.com:81/01/09506000134352")
for (bad in c("ftp://example.com/01/09506000134352", "https://example.com /01/09506000134352", "https://example.com\\01/09506000134352", "/01/09506000134352")) .rg_error(parse_gs1_digital_link(bad), detail = "GS1_DIGITAL_LINK_INVALID_URI")
.rg_check(length(validate_gs1_digital_link(sub("https", "http", unknown))$warnings) == 2L)
.rg_check(!validate_gs1_digital_link(base, normalize = TRUE)$ok)
.rg_error(normalize_gs1_digital_link(base, mode = "other"))
# Colors, alpha composition, SVG and geometry.
.rg_same(parse_color("#123"), c(17, 34, 51, 255))
.rg_same(parse_color("#1234"), c(17, 34, 51, 68))
.rg_same(parse_color("#12345678"), c(18, 52, 86, 120))
.rg_same(parse_color(" white "), rep(255, 4))
.rg_same(parse_color("transparent"), rep(0, 4))
.rg_check(is.null(parse_color("rebeccapurple")))
.rg_error(parse_color("rebeccapurple", TRUE), "INVALID_COLOR")
for (bad in list(NA_character_, character(), c("red", "blue"), 123, "", "#12", "#zzzzzz", "red\" onload=\"x", "url(x)", "rgb(0,0,0)", paste0(rep("a", 65), collapse = ""))) .rg_error(parse_color(bad), "INVALID_COLOR")
.rg_error(parse_color("black", NA), "INVALID_INPUT")
.rg_same(contrast_ratio("black", "white"), 21)
.rg_same(contrast_ratio("transparent", "white"), 1)
.rg_same(contrast_ratio("#00000080", "white"), 4.004106956614851)
.rg_error(contrast_ratio(c(0, 0, 0, 256), "white"), "INVALID_COLOR")
.rg_error(contrast_ratio(c(0, 0, 0, NA), "white"), "INVALID_COLOR")
mat <- matrix(c(TRUE, FALSE, FALSE, TRUE), 2, 2)
.rg_same(render_dimensions(mat, margin = 2, scale = 3)$width, 18)
.rg_same(render_dimensions(mat, margin = 2, scale = 3, dpi = 254)$module_size_mm, 0.3)
for (bad in list(NA, TRUE, Inf, -1, 1.5, c(1, 2))) .rg_error(render_dimensions(mat, margin = bad), "INVALID_INPUT")
for (bad in list(NA, TRUE, Inf, 0, -1, 1.5, c(1, 2))) .rg_error(render_dimensions(mat, scale = bad), "INVALID_INPUT")
for (bad in list(NA, TRUE, Inf, 0, -1, c(1, 2), .Machine$double.xmin)) .rg_error(render_dimensions(mat, dpi = bad), "INVALID_INPUT")
for (bad in list(matrix(1, 2, 2), matrix(NA, 2, 2), matrix(TRUE, 2, 3), matrix(TRUE, 178, 178), matrix(TRUE, 0, 0), TRUE)) .rg_error(to_svg(bad), "INVALID_INPUT")
.rg_error(render_dimensions(mat, margin = 1e9), "INVALID_INPUT")
.rg_error(render_dimensions(mat, scale = 1e9), "INVALID_INPUT")
.rg_error(to_pixels(mat, scale = 2049), "INVALID_INPUT")
.rg_error(to_png(mat, foreground = "red"), "INVALID_COLOR")
.rg_error(to_data_url(mat, format = "jpg"), "INVALID_OUTPUT")
.rg_error(render(mat, format = NA), "INVALID_OUTPUT")
svg <- to_svg(mat, margin = 0, scale = 1, foreground = "red", background = "transparent")
.rg_check(grepl('d="M0,0h1v1h-1zM1,1h1v1h-1z"', svg, fixed = TRUE))
.rg_check(grepl('fill="red"', svg, fixed = TRUE))
.rg_check(grepl('d=""', to_svg(matrix(FALSE, 1, 1)), fixed = TRUE))
.rg_check(!grepl("e+", to_svg(matrix(TRUE, 1, 1), margin = 100000, scale = 1000), fixed = TRUE))
pixels <- to_pixels(mat, margin = 0, scale = 1, foreground = "#1234", background = "#abcd")
.rg_same(as.integer(pixels$pixels), c(17,34,51,68,170,187,204,221,170,187,204,221,17,34,51,68))
.rg_same(render_rgba(mat, margin = 0, scale = 1)$data, to_pixels(mat, margin = 0, scale = 1)$pixels)
.rg_same(.png_crc(charToRaw("123456789")), 3421780262)
.rg_same(.png_adler(charToRaw("Wikipedia")), 300286872)
.rg_same(.base64_encode(charToRaw("f")), "Zg==")
.rg_same(.base64_encode(charToRaw("fo")), "Zm8=")
.rg_same(.base64_encode(charToRaw("foo")), "Zm9v")
.rg_same(.base64_encode(raw()), "")
.rg_check(startsWith(to_svg_data_url(mat), "data:image/svg+xml;charset=utf-8,%3Csvg"))
.rg_check(startsWith(to_png_data_url(mat, scale = 1), "data:image/png;base64,iVBORw0KGgo"))
# Independently read PNG structure and stored DEFLATE; no image package needed.
.rg_png <- function(matrix, scale) {
  png <- to_png(matrix, margin = 1, scale = scale, foreground = "#01020380", background = "#fafbfcfd")
  pix <- to_pixels(matrix, margin = 1, scale = scale, foreground = "#01020380", background = "#fafbfcfd")
  be <- function(x) sum(as.integer(x) * c(16777216,65536,256,1))
  .rg_same(as.integer(png[1:8]), c(137,80,78,71,13,10,26,10)); at <- 9L; kinds <- character(); idat <- raw()
  while (at <= length(png)) {
    n <- be(png[at:(at+3L)]); kind <- rawToChar(png[(at+4L):(at+7L)]); data <- if (n) png[seq.int(at+8L,at+7L+n)] else raw()
    .rg_same(.png_crc(c(charToRaw(kind),data)), be(png[seq.int(at+8L+n,at+11L+n)]))
    if (kind == "IHDR") { .rg_same(be(data[1:4]), pix$width); .rg_same(as.integer(data[9:13]),c(8,6,0,0,0)) }
    if (kind == "IDAT") idat <- c(idat,data)
    kinds <- c(kinds,kind); at <- at+12L+n
  }
  .rg_same(kinds,c("IHDR","IDAT","IEND")); .rg_same(as.integer(idat[1:2]),c(120,1)); at <- 3L; scan <- raw()
  repeat {
    final <- as.integer(idat[at]); .rg_check(final %in% 0:1)
    n <- as.integer(idat[at+1L])+256L*as.integer(idat[at+2L]); inv <- as.integer(idat[at+3L])+256L*as.integer(idat[at+4L])
    .rg_same(n+inv,65535L); scan <- c(scan,idat[seq.int(at+5L,at+4L+n)]); at <- at+5L+n
    if (final == 1L) break
  }
  .rg_same(.png_adler(scan),be(idat[at:(at+3L)])); stride <- pix$width*4L+1L
  .rg_check(all(scan[seq.int(1L,length(scan),by=stride)]==as.raw(0L)))
  .rg_same(scan[-seq.int(1L,length(scan),by=stride)],pix$pixels)
}
.rg_png(mat, 1L)
.rg_png(mat, 40L) # Stored DEFLATE crosses its 65,535-byte boundary.
if (exists("generate", mode = "function")) {
  qr <- generate("SpecQR render integration", scale = 2, print_dpi = 300)
  .rg_same(render_dimensions(qr)$module_pixels, 2)
  .rg_same(render_dimensions(qr)$dpi, 300)
  .rg_same(to_pixels(qr)$pixels, to_pixels(qr$matrix, scale = 2)$pixels)
  bad <- qr; bad$version <- NA_integer_; .rg_error(to_svg(bad), "INVALID_VERSION")
}
.rg_error(create_gs1_element_string(list(list(air = "10", value = "A"))))
.rg_error(create_gs1_element_string(list(structure(list("10", "21", "A"), names = c("ai", "ai", "value")))))
.rg_check(!validate_gs1_elements(items, context = matrix("element-string", 1, 1))$ok)
.rg_error(to_svg(list(matrixExtra = mat)), "INVALID_INPUT")
.rg_error(to_svg(list(matrix = mat, options = "bad")), "INVALID_INPUT")
.rg_error(to_svg(list(matrix = mat, options = structure(list(1, 2), names = c("margin", "margin")))), "INVALID_INPUT")
cat("Render/GS1:", .rg_checks, "checks passed\n")
